# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Wangkajunga spellchecker"
mpj = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Wangkajunga, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
mpj = "TRANSLATE: A spellchecker for Wangkajunga, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.mpj"

[windows]
system_product_code = "{499EE785-A495-4A23-9C94-70734A16F15C}_is1"

[package.speller]
name = "Wangkajunga"
version = "0.1.0"

[package.grammar]
name = "Wangkajunga"
version = "0.1.0"

[package.tts-text-proc]
name = "Wangkajunga"
version = "0.1.0"
