template = ""
rev_id = 89
template_sha = "af8541df7c1e45fc9cc76282cc77195dbf8d95b6"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mpj"
__UND2C__ = "mpj"
__UNDEFINED__ = "Wangkajunga"
__UND__ = "mpj"
