template = ""
rev_id = 85
template_sha = "9ed3df3b4a68b795ab2c3d59873602b657210547"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mpj"
__UND2C__ = "mpj"
__UNDEFINED__ = "Wangkajunga"
__UND__ = "mpj"
