template = ""
rev_id = 117
template_sha = "32744b7a96e8c2391415cb499d7f5f028750e3d4"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mpj"
__UND2C__ = "mpj"
__UNDEFINED__ = "Wangkajunga"
__UND__ = "mpj"
